print(3 + 4) 
print(3 - 4) 
print(3 * 4) 
print(3 % 4)
print(3 / 4)
print(3 ** 4)
print(3 // 4)
print ('your name:Paula')
print ('your family name:García')
print ('your country:España')
print ('I am enjoying 30 days of python')
print(type('10'))
print(type('9.8'))
print(type('3.14'))
print(type('4-4j'))
print(type(['Asabeneh','Python','Finland']))
print(type('your name'))
print(type('your family name'))
print(type('your country'))

print(type(10))         
print(type(3.14))        
print(type(1 + 3j))      
print(type('Asabeneh'))  
print(type([1, 2, 3]))   
print(type({'name':'Asabeneh'})) 
print(type({9.8, 3.14, 2.7})) 

print(2 - 10)
print(3 - 8)